<?php

return [
    'event' => [
        'name' => 'ProBiz Awards 2026 Dubai',
        'eyebrow' => 'PROBIZ AWARDS 2026 DUBAI',
        'tagline' => 'Celebrating Excellence Across UAE Business',
        'date' => '11 December 2026',
        'venue_short' => 'Falcon Ballroom, Le Meridien Dubai Hotel & Conference Centre',
        'venue' => 'Falcon Ballroom 1 + 2, Le Meridien Dubai Hotel & Conference Centre, Airport Road, Dubai, UAE',
        'footer_summary' => 'ProBiz Awards 2026 Dubai celebrates businesses, entrepreneurs and professionals across the UAE through industry recognition, brand visibility and an evening of networking and celebration.',
        'finalist_price' => 'AED 5,000',
        'finalist_invitations' => '3 gala dinner invitations',
    ],

    'images' => [
        'base' => 'assets/frontend/images/ProBiz_Images_Only',
        'hero_desktop' => 'hero-desktop.jpg',
        'hero_mobile' => 'hero-mobile.jpg',
        'inner_masthead' => 'inner-masthead.jpg',
        'restaurant_hero' => 'restaurant-hero.jpg',
        'gala' => 'gala-concept.jpg',
        'networking' => 'networking-concept.jpg',
        'media' => 'media-concept.jpg',
        'brochure' => 'brochure-mockup.png',
    ],

    'pillars' => [
        [
            'id' => 'P01',
            'slug' => 'business-entrepreneurship',
            'title' => 'Business & Entrepreneurship',
            'theme' => 'Visionary of the Year',
            'description' => 'Celebrating entrepreneurs, business leaders and enterprises contributing to the UAE business community.',
            'image' => '01-business.jpg',
            'awards' => [
                ['id' => 'M01', 'slug' => 'visionary-entrepreneur-of-the-year', 'title' => 'Visionary Entrepreneur of the Year', 'description' => 'Recognising an entrepreneur who combines a clear business vision with purposeful leadership, original thinking and demonstrated progress.'],
                ['id' => 'M02', 'slug' => 'business-leader-of-the-year', 'title' => 'Business Leader of the Year', 'description' => 'Recognising a leader whose decisions, team development and business achievements show a meaningful contribution to their organisation.'],
                ['id' => 'M03', 'slug' => 'emerging-enterprise-of-the-year', 'title' => 'Emerging Enterprise of the Year', 'description' => 'Recognising a developing enterprise with a distinctive offering, evidence of progress and a clear direction for sustainable growth.'],
                ['id' => 'M04', 'slug' => 'women-in-business-excellence-award', 'title' => 'Women in Business Excellence Award', 'description' => 'Celebrating a woman whose leadership, enterprise or professional contribution has created a meaningful impact in business.'],
                ['id' => 'M05', 'slug' => 'corporate-legacy-award', 'title' => 'Corporate Legacy Award', 'description' => 'Recognising an established organisation with a sustained contribution to its industry, customers and business community.'],
            ],
        ],
        [
            'id' => 'P02',
            'slug' => 'food-chef-hospitality',
            'title' => 'Food, Chef & Hospitality',
            'theme' => 'Master of Craft',
            'description' => 'Recognising the talent, leadership and ideas behind memorable dining and hospitality experiences.',
            'image' => '02-hospitality.jpg',
            'awards' => [
                ['id' => 'M06', 'slug' => 'chef-of-the-year', 'title' => 'Chef of the Year', 'description' => 'Celebrating a chef whose culinary skill, originality and consistency create a distinctive dining experience.'],
                ['id' => 'M07', 'slug' => 'restaurant-of-the-year', 'title' => 'Restaurant of the Year', 'description' => 'Recognising a restaurant that brings together food quality, service, atmosphere and a compelling overall guest experience.'],
                ['id' => 'M08', 'slug' => 'hospitality-leader-of-the-year', 'title' => 'Hospitality Leader of the Year', 'description' => 'Recognising a hospitality professional whose leadership strengthens service standards, team performance and guest experience.'],
                ['id' => 'M09', 'slug' => 'culinary-innovation-award', 'title' => 'Culinary Innovation Award', 'description' => 'Celebrating a culinary concept, technique or offering that introduces a fresh approach and a meaningful improvement to the dining experience.'],
                ['id' => 'M10', 'slug' => 'hospitality-innovation-award', 'title' => 'Hospitality Innovation Award', 'description' => 'Recognising an initiative that improves hospitality operations, guest service or the way an experience is delivered.'],
            ],
        ],
        [
            'id' => 'P03',
            'slug' => 'fashion-beauty',
            'title' => 'Fashion & Beauty',
            'theme' => 'Icon of Style',
            'description' => 'Celebrating creativity, professional expertise and distinctive contributions across fashion and beauty.',
            'image' => '03-fashion.jpg',
            'awards' => [
                ['id' => 'M11', 'slug' => 'designer-of-the-year', 'title' => 'Designer of the Year', 'description' => 'Recognising a designer whose creative direction, craftsmanship and body of work show a distinctive contribution to fashion.'],
                ['id' => 'M12', 'slug' => 'beauty-brand-of-the-year', 'title' => 'Beauty Brand of the Year', 'description' => 'Celebrating a beauty brand with a clear identity, thoughtful products or services and a strong customer experience.'],
                ['id' => 'M13', 'slug' => 'style-icon-of-the-year', 'title' => 'Style Icon of the Year', 'description' => 'Recognising an individual with a distinctive style identity and a positive contribution to the fashion and lifestyle community.'],
                ['id' => 'M14', 'slug' => 'fashion-influencer-of-the-year', 'title' => 'Fashion Influencer of the Year', 'description' => 'Recognising a creator whose original fashion content, audience engagement and professional approach make a meaningful contribution.'],
                ['id' => 'M15', 'slug' => 'beauty-expert-of-the-year', 'title' => 'Beauty Expert of the Year', 'description' => 'Celebrating a beauty professional whose expertise, client care and standard of work demonstrate professional excellence.'],
            ],
        ],
        [
            'id' => 'P04',
            'slug' => 'healthcare-wellness',
            'title' => 'Healthcare & Wellness',
            'theme' => 'Guardian of Wellbeing',
            'description' => 'Recognising professionals, brands and initiatives contributing to healthcare, fitness and wellbeing.',
            'image' => '04-healthcare.jpg',
            'awards' => [
                ['id' => 'M16', 'slug' => 'medical-professional-of-the-year', 'title' => 'Medical Professional of the Year', 'description' => 'Recognising a medical professional for their contribution to patient care, professional practice and service improvement.'],
                ['id' => 'M17', 'slug' => 'wellness-brand-of-the-year', 'title' => 'Wellness Brand of the Year', 'description' => 'Celebrating a wellness brand with a considered approach to service quality, customer care and wellbeing.'],
                ['id' => 'M18', 'slug' => 'healthcare-innovation-award', 'title' => 'Healthcare Innovation Award', 'description' => 'Recognising an initiative that demonstrates a useful improvement in healthcare delivery, access, experience or operations.'],
                ['id' => 'M19', 'slug' => 'fitness-wellbeing-icon', 'title' => 'Fitness & Wellbeing Icon', 'description' => 'Celebrating an individual whose work encourages positive participation in fitness and wellbeing.'],
                ['id' => 'M20', 'slug' => 'mental-health-advocate-of-the-year', 'title' => 'Mental Health Advocate of the Year', 'description' => 'Recognising a person whose advocacy, education or community work supports greater understanding of mental wellbeing.'],
            ],
        ],
        [
            'id' => 'P05',
            'slug' => 'lifestyle-luxury-innovation',
            'title' => 'Lifestyle, Luxury & Innovation',
            'theme' => 'Pioneer of Excellence',
            'description' => 'Celebrating distinctive brands, ideas and experiences across lifestyle and luxury.',
            'image' => '05-luxury.jpg',
            'awards' => [
                ['id' => 'M21', 'slug' => 'luxury-brand-of-the-year', 'title' => 'Luxury Brand of the Year', 'description' => 'Recognising a luxury brand that combines a clear identity, craftsmanship, service quality and a distinctive customer experience.'],
                ['id' => 'M22', 'slug' => 'innovator-of-the-year', 'title' => 'Innovator of the Year', 'description' => 'Celebrating an individual whose original idea or approach creates a demonstrated improvement in their field.'],
                ['id' => 'M23', 'slug' => 'lifestyle-influencer-of-the-year', 'title' => 'Lifestyle Influencer of the Year', 'description' => 'Recognising a creator whose original lifestyle content, audience connection and professional standards distinguish their work.'],
                ['id' => 'M24', 'slug' => 'sustainable-luxury-award', 'title' => 'Sustainable Luxury Award', 'description' => 'Recognising a luxury initiative supported by evidence of responsible materials, operations or resource use.'],
                ['id' => 'M25', 'slug' => 'luxury-retail-excellence-award', 'title' => 'Luxury Retail Excellence Award', 'description' => 'Celebrating a luxury retailer for product presentation, customer service and overall shopping experience.'],
            ],
        ],
        [
            'id' => 'P06',
            'slug' => 'real-estate-property',
            'title' => 'Real Estate & Property',
            'theme' => 'Architect of Vision',
            'description' => 'Recognising professionals, developments and ideas contributing to the UAE property sector.',
            'image' => '06-property.jpg',
            'awards' => [
                ['id' => 'M26', 'slug' => 'real-estate-developer-of-the-year', 'title' => 'Real Estate Developer of the Year', 'description' => 'Recognising a developer for project quality, delivery approach and contribution to the built environment.'],
                ['id' => 'M27', 'slug' => 'real-estate-agent-broker-of-the-year', 'title' => 'Real Estate Agent/Broker of the Year', 'description' => 'Celebrating an agent or agency whose professional service, market understanding and client care demonstrate strong performance.'],
                ['id' => 'M28', 'slug' => 'luxury-property-of-the-year', 'title' => 'Luxury Property of the Year', 'description' => 'Recognising a named property with distinctive design, quality, amenities and an exceptional residential or guest experience.'],
                ['id' => 'M29', 'slug' => 'real-estate-innovation-award', 'title' => 'Real Estate Innovation Award', 'description' => 'Celebrating a solution or initiative that improves property services, development processes or the customer experience.'],
                ['id' => 'M30', 'slug' => 'sustainable-development-award', 'title' => 'Sustainable Development Award', 'description' => 'Recognising a property development supported by evidence of environmental consideration and responsible design or operation.'],
            ],
        ],
        [
            'id' => 'P07',
            'slug' => 'opticals-eyewear',
            'title' => 'Opticals & Eyewear',
            'theme' => 'Vision of Clarity',
            'description' => 'Celebrating professional care, design and customer experience across optical services and eyewear.',
            'image' => '07-opticals.jpg',
            'awards' => [
                ['id' => 'M31', 'slug' => 'optical-brand-of-the-year', 'title' => 'Optical Brand of the Year', 'description' => 'Recognising an optical brand with a clear offering, consistent quality and a considered customer experience.'],
                ['id' => 'M32', 'slug' => 'eyewear-designer-of-the-year', 'title' => 'Eyewear Designer of the Year', 'description' => 'Celebrating a designer whose eyewear combines creative identity, craftsmanship and practical design.'],
                ['id' => 'M33', 'slug' => 'optometrist-of-the-year', 'title' => 'Optometrist of the Year', 'description' => 'Recognising an optometrist for professional practice, patient communication and contribution to eye care.'],
                ['id' => 'M34', 'slug' => 'optical-retail-excellence-award', 'title' => 'Optical Retail Excellence Award', 'description' => 'Celebrating an optical retailer for product guidance, service standards and overall customer journey.'],
                ['id' => 'M35', 'slug' => 'innovation-in-eye-care-award', 'title' => 'Innovation in Eye Care Award', 'description' => 'Recognising an evidence-supported initiative that improves eye-care services, access, experience or delivery.'],
            ],
        ],
        [
            'id' => 'P08',
            'slug' => 'electronics-technology',
            'title' => 'Electronics & Technology',
            'theme' => 'Pioneer of Innovation',
            'description' => 'Recognising brands and solutions shaping consumer technology and connected living.',
            'image' => '08-electronics.jpg',
            'awards' => [
                ['id' => 'M36', 'slug' => 'electronics-brand-of-the-year', 'title' => 'Electronics Brand of the Year', 'description' => 'Celebrating an electronics brand for product offering, customer experience and contribution to its market.'],
                ['id' => 'M37', 'slug' => 'consumer-tech-innovation-award', 'title' => 'Consumer Tech Innovation Award', 'description' => 'Recognising a consumer technology product or solution that addresses a real user need through a useful innovation.'],
                ['id' => 'M38', 'slug' => 'smart-home-excellence-award', 'title' => 'Smart Home Excellence Award', 'description' => 'Celebrating a smart-home product or solution that combines usability, integration and practical value for residents.'],
                ['id' => 'M39', 'slug' => 'electronics-retailer-of-the-year', 'title' => 'Electronics Retailer of the Year', 'description' => 'Recognising an electronics retailer for product guidance, shopping experience and after-sales support.'],
                ['id' => 'M40', 'slug' => 'emerging-tech-startup-of-the-year', 'title' => 'Emerging Tech Startup of the Year', 'description' => 'Celebrating a developing technology business with a relevant solution, evidence of progress and a clear market opportunity.'],
            ],
        ],
        [
            'id' => 'P09',
            'slug' => 'travel-tourism-resorts',
            'title' => 'Travel, Tourism & Resorts',
            'theme' => 'Journey of Distinction',
            'description' => 'Celebrating organisations and experiences contributing to travel, tourism and hospitality.',
            'image' => '09-travel.jpg',
            'awards' => [
                ['id' => 'M41', 'slug' => 'resort-of-the-year', 'title' => 'Resort of the Year', 'description' => 'Recognising a resort for service, setting, facilities and overall guest experience.'],
                ['id' => 'M42', 'slug' => 'travel-agency-of-the-year', 'title' => 'Travel Agency of the Year', 'description' => 'Celebrating a travel agency for planning expertise, customer support and quality of travel arrangements.'],
                ['id' => 'M43', 'slug' => 'airline-excellence-award', 'title' => 'Airline Excellence Award', 'description' => 'Recognising an airline for its contribution to passenger experience, service quality and customer support.'],
                ['id' => 'M44', 'slug' => 'tourism-board-of-the-year', 'title' => 'Tourism Board of the Year', 'description' => 'Celebrating a tourism board for destination promotion, visitor engagement and contribution to tourism development.'],
                ['id' => 'M45', 'slug' => 'luxury-travel-experience-award', 'title' => 'Luxury Travel Experience Award', 'description' => 'Recognising a distinctive travel experience combining thoughtful planning, service quality and memorable guest experiences.'],
            ],
        ],
        [
            'id' => 'P10',
            'slug' => 'it-software-digital-platforms',
            'title' => 'IT, Software & Digital Platforms',
            'theme' => 'Digital Trailblazer',
            'description' => 'Recognising digital businesses and products that create useful experiences for customers and organisations.',
            'image' => '10-digital.jpg',
            'awards' => [
                ['id' => 'M46', 'slug' => 'software-company-of-the-year', 'title' => 'Software Company of the Year', 'description' => 'Celebrating a software company for solutions, delivery standards, customer support and demonstrated client value.'],
                ['id' => 'M47', 'slug' => 'e-commerce-platform-of-the-year', 'title' => 'E-commerce Platform of the Year', 'description' => 'Recognising an e-commerce platform for shopping experience, operational reliability and value for customers or sellers.'],
                ['id' => 'M48', 'slug' => 'mobile-app-of-the-year', 'title' => 'Mobile App of the Year', 'description' => 'Celebrating a mobile application that combines useful functionality, accessible design and a strong user experience.'],
                ['id' => 'M49', 'slug' => 'digital-platform-innovation-award', 'title' => 'Digital Platform Innovation Award', 'description' => 'Recognising a digital platform that introduces a useful improvement in how users connect, transact or access services.'],
                ['id' => 'M50', 'slug' => 'best-loyalty-rewards-program', 'title' => 'Best Loyalty & Rewards Program', 'description' => 'Celebrating a loyalty programme that offers clear customer value, an accessible experience and meaningful engagement.'],
            ],
        ],
    ],

    'restaurant_awards' => [
        ['id' => 'R01', 'slug' => 'best-pakistani-restaurant', 'title' => 'Best Pakistani Restaurant', 'description' => 'Recognising a Pakistani restaurant for its food, hospitality and a consistent experience that reflects its culinary identity.'],
        ['id' => 'R02', 'slug' => 'best-indian-restaurant', 'title' => 'Best Indian Restaurant', 'description' => 'Celebrating an Indian restaurant that brings together distinctive food, reliable service and a memorable dining experience.'],
        ['id' => 'R03', 'slug' => 'best-arabic-restaurant', 'title' => 'Best Arabic Restaurant', 'description' => 'Recognising an Arabic restaurant for its cuisine, hospitality and overall guest experience.'],
        ['id' => 'R04', 'slug' => 'best-asian-restaurant', 'title' => 'Best Asian Restaurant', 'description' => 'Celebrating an Asian restaurant with a distinctive culinary offering, consistent quality and thoughtful service.'],
        ['id' => 'R05', 'slug' => 'best-turkish-restaurant', 'title' => 'Best Turkish Restaurant', 'description' => 'Recognising a Turkish restaurant for its food, cultural character and guest experience.'],
        ['id' => 'R06', 'slug' => 'best-fine-dining-restaurant', 'title' => 'Best Fine Dining Restaurant', 'description' => 'Celebrating a restaurant where culinary execution, service, atmosphere and attention to detail form a refined dining experience.'],
        ['id' => 'R07', 'slug' => 'best-casual-dining-restaurant', 'title' => 'Best Casual Dining Restaurant', 'description' => 'Recognising an approachable dining concept with consistent food, welcoming service and everyday customer appeal.'],
        ['id' => 'R08', 'slug' => 'best-cafe', 'title' => 'Best Cafe', 'description' => 'Celebrating a cafe for drinks, food offering, atmosphere and customer experience.'],
        ['id' => 'R09', 'slug' => 'best-bakery-dessert-brand', 'title' => 'Best Bakery & Dessert Brand', 'description' => 'Recognising a bakery or dessert brand for its product quality, creativity and customer experience.'],
        ['id' => 'R10', 'slug' => 'best-quick-service-restaurant', 'title' => 'Best Quick Service Restaurant', 'description' => 'Celebrating a quick-service restaurant for consistent quality, efficient service and a convenient customer journey.'],
        ['id' => 'R11', 'slug' => 'best-family-restaurant', 'title' => 'Best Family Restaurant', 'description' => 'Recognising a restaurant that thoughtfully serves families through its menu, facilities, atmosphere and service.'],
        ['id' => 'R12', 'slug' => 'best-rooftop-dining', 'title' => 'Best Rooftop Dining', 'description' => 'Celebrating a rooftop dining venue that combines its setting with food, service and an engaging guest experience.'],
        ['id' => 'R13', 'slug' => 'best-customer-experience', 'title' => 'Best Customer Experience', 'description' => 'Recognising a restaurant whose customer care creates a consistent, welcoming experience across the guest journey.'],
        ['id' => 'R14', 'slug' => 'best-new-restaurant', 'title' => 'Best New Restaurant', 'description' => 'Celebrating a newly opened restaurant with a distinctive concept and a promising guest experience.'],
        ['id' => 'R15', 'slug' => 'best-restaurant-interior-ambience', 'title' => 'Best Restaurant Interior & Ambience', 'description' => 'Recognising a restaurant whose interior, lighting, layout and atmosphere strengthen its dining concept.'],
        ['id' => 'R16', 'slug' => 'best-healthy-dining-concept', 'title' => 'Best Healthy Dining Concept', 'description' => 'Celebrating a dining concept with a clear approach to balanced menu choices, ingredient information and customer needs.'],
        ['id' => 'R17', 'slug' => 'best-homegrown-restaurant-brand', 'title' => 'Best Homegrown Restaurant Brand', 'description' => 'Recognising a restaurant brand founded in the UAE with a distinctive identity and contribution to the local dining scene.'],
        ['id' => 'R18', 'slug' => 'best-restaurant-chain', 'title' => 'Best Restaurant Chain', 'description' => 'Celebrating a restaurant group or chain for consistency, service and brand experience across its locations.'],
        ['id' => 'R19', 'slug' => 'best-catering-company', 'title' => 'Best Catering Company', 'description' => 'Recognising a catering business for food quality, planning, service and delivery of client events.'],
        ['id' => 'R20', 'slug' => 'peoples-choice-restaurant', 'title' => "People's Choice Restaurant", 'description' => 'Celebrating the restaurant selected through the published public voting process, subject to vote validation and eligibility checks.'],
    ],

    'sponsor_packages' => [
        ['id' => 'title-partner', 'title' => 'Title Partner', 'price' => 'AED 45,000', 'description' => 'Highest partner positioning; main-stage and sponsor-wall branding; 8 VIP gala seats; award presentation opportunity; dedicated social announcement; premium networking access.'],
        ['id' => 'platinum-partner', 'title' => 'Platinum Partner', 'price' => 'AED 30,000', 'description' => 'Premium logo placement; stage and sponsor-wall visibility; 6 VIP gala seats; award presentation opportunity; 4 social media features.'],
        ['id' => 'gold-partner', 'title' => 'Gold Partner', 'price' => 'AED 20,000', 'description' => 'Gold Partner recognition; sponsor-wall branding; 4 gala seats; 3 social media features; on-screen event recognition.'],
        ['id' => 'category-partner', 'title' => 'Category Partner', 'price' => 'AED 10,000', 'description' => 'Official association with one award category; category award presentation opportunity; 3 gala seats; 2 social media features.'],
        ['id' => 'table-partner', 'title' => 'Table Partner', 'price' => 'AED 7,500', 'description' => 'Corporate Table Partner recognition; 6 gala seats; branded table identification; website partner listing.'],
    ],
];
